### ISSUE TITLE
4G-wifi issue: disable ContinualGatheringPolicy , user2 can not publish to user1 after user1 change Network

### ISSUE THREAD

**Issue by zhangyihui1** [open-media-streamer/oms-client-android#63]
1: disable ContinualGatheringPolicy and set turn server
2: use1 and user2 connect server
3: user1 publish localstream to user1
4: user1 switch 4G -> wifi ,or wifi -> 4G
5: user2 publish localstream to user1

expect  user2 publish success ,but actual user2 can not publish to user1

**Comment by hankzh89** [comment]
Incorrect expectation.
